version: '3.8'

services:
  php-apache:
    build:
      context: ./backend/php
    ports:
      - "8080:80"  # Expose Apache on port 8080
    volumes:
      - ./backend/php:/var/www/html/php  # Mount PHP source code
      - ./website:/var/www/html/  # Mount website static files
    depends_on:
      - mysql  # Ensure MySQL is running
    networks:
      - app-network

  nodejs:
    build:
      context: ./backend/nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./backend/nodejs:/usr/src/app          # Mount source code
      - /usr/src/app/node_modules             # Preserve `node_modules` in the container
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Blitzkrieg
      MYSQL_USER: pilot
      MYSQL_PASSWORD: pilot
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent data storage
      - ./database:/docker-entrypoint-initdb.d  # Mount initialization scripts
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:

